wip ci test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,69 +3,71 @@ version: 2
 jobs:
  # must be called build for local circle cli to work
  # is actually unit tests
- build:
-  docker:
-   - image: holochain/holochain-rust:latest
-  resource_class: large
-  steps:
-   - checkout
-   - run: nix-shell --run hc-rust-test
+ # build:
+ #  docker:
+ #   - image: holochain/holochain-rust:latest
+ #  resource_class: large
+ #  steps:
+ #   - checkout
+ #   - run: nix-shell --run hc-rust-test
 
- fmt:
-  docker:
-   - image: holochain/holochain-rust:latest
-  steps:
-   - checkout
-   - run: nix-shell --run hc-rust-fmt-check
-   # don't allow unpinned deps
-   - run:
-      name: no unpinnned deps
-      command: |
-        # temporary avoid build fails due to greps
-        set +eo pipefail
-        export UNPINNED=`nix-shell --run hc-rust-manifest-list-unpinned`
-        set -eo pipefail
-        if [[ $UNPINNED ]]
-        then
-         echo "unpinned deps must be empty:"
-         echo "$UNPINNED"
-         exit 1
-        fi
-   # don't allow changelog root items with no PR reference
-   - run:
-      name: no changelogs without PR references
-      command: |
-        # temporary avoid build fails due to greps
-        set +eo pipefail
-        export UNREFERENCED=`nix-shell --run hc-release-docs-changelog-list-missing-references`
-        set -eo pipefail
-        if [[ $UNREFERENCED ]]
-        then
-          echo "all root level changelog items need a PR reference:"
-          echo "$UNREFERENCED"
-          exit 1
-        fi
+ # fmt:
+ #  docker:
+ #   - image: holochain/holochain-rust:latest
+ #  steps:
+ #   - checkout
+ #   - run: nix-shell --run hc-rust-fmt-check
+ #   # don't allow unpinned deps
+ #   - run:
+ #      name: no unpinnned deps
+ #      command: |
+ #        # temporary avoid build fails due to greps
+ #        set +eo pipefail
+ #        export UNPINNED=`nix-shell --run hc-rust-manifest-list-unpinned`
+ #        set -eo pipefail
+ #        if [[ $UNPINNED ]]
+ #        then
+ #         echo "unpinned deps must be empty:"
+ #         echo "$UNPINNED"
+ #         exit 1
+ #        fi
+ #   # don't allow changelog root items with no PR reference
+ #   - run:
+ #      name: no changelogs without PR references
+ #      command: |
+ #        # temporary avoid build fails due to greps
+ #        set +eo pipefail
+ #        export UNREFERENCED=`nix-shell --run hc-release-docs-changelog-list-missing-references`
+ #        set -eo pipefail
+ #        if [[ $UNREFERENCED ]]
+ #        then
+ #          echo "all root level changelog items need a PR reference:"
+ #          echo "$UNREFERENCED"
+ #          exit 1
+ #        fi
 
-   # flag any references to a nightly version in a readme other than the
-   # ${date} in nix-shell
-   - run:
-      name: no readmes with bad rust nightly versions
-      command: |
-        # temporary avoid build fails due to greps
-        set +eo pipefail
-        export BAD_NIGHTLY=`nix-shell --run hc-release-docs-readme-list-stale-nightlies`
-        set -eo pipefail
-        if [[ $BAD_NIGHTLY ]]
-        then
-          echo "there is an incorrect nightly version in a readme file:"
-          echo $BAD_NIGHTLY
-          exit 1
-        fi
+ #   # flag any references to a nightly version in a readme other than the
+ #   # ${date} in nix-shell
+ #   - run:
+ #      name: no readmes with bad rust nightly versions
+ #      command: |
+ #        # temporary avoid build fails due to greps
+ #        set +eo pipefail
+ #        export BAD_NIGHTLY=`nix-shell --run hc-release-docs-readme-list-stale-nightlies`
+ #        set -eo pipefail
+ #        if [[ $BAD_NIGHTLY ]]
+ #        then
+ #          echo "there is an incorrect nightly version in a readme file:"
+ #          echo $BAD_NIGHTLY
+ #          exit 1
+ #        fi
 
  app-spec-tests:
   docker:
    - image: holochain/holochain-rust:latest
   resource_class: xlarge
+  environment:
+    TMPDIR: /tmp
   steps:
    - checkout
 
@@ -73,110 +75,110 @@ jobs:
        name: app spec tests
        command: nix-shell --run hc-app-spec-test
 
- app-spec-proc-tests:
-  docker:
-   - image: holochain/holonix:latest
-  resource_class: xlarge
-  steps:
-   - checkout
+ # app-spec-proc-tests:
+ #  docker:
+ #   - image: holochain/holonix:latest
+ #  resource_class: xlarge
+ #  steps:
+ #   - checkout
 
-   - run:
-       name: proc macro app spec tests
-       command: nix-shell --run hc-app-spec-test-proc
+ #   - run:
+ #       name: proc macro app spec tests
+ #       command: nix-shell --run hc-app-spec-test-proc
 
- cluster-tests:
-  docker:
-   - image: holochain/holochain-rust:latest
-  resource_class: xlarge
-  steps:
-   - checkout
+ # cluster-tests:
+ #  docker:
+ #   - image: holochain/holochain-rust:latest
+ #  resource_class: xlarge
+ #  steps:
+ #   - checkout
 
-   - run:
-       name: app spec cluster tests
-       command: nix-shell --run hc-app-spec-cluster-test
+ #   - run:
+ #       name: app spec cluster tests
+ #       command: nix-shell --run hc-app-spec-cluster-test
 
- cli-tests:
-  docker:
-   - image: holochain/holochain-rust:latest
-  steps:
-   - checkout
+ # cli-tests:
+ #  docker:
+ #   - image: holochain/holochain-rust:latest
+ #  steps:
+ #   - checkout
 
-   - run:
-       name: install cli
-       command: nix-shell --run hc-cli-install
+ #   - run:
+ #       name: install cli
+ #       command: nix-shell --run hc-cli-install
 
-   - run:
-      name: test cli
-      command: nix-shell --run hc-cli-test
+ #   - run:
+ #      name: test cli
+ #      command: nix-shell --run hc-cli-test
 
- wasm-conductor-tests:
-  docker:
-   - image: holochain/holochain-rust:latest
-  steps:
-   - checkout
+ # wasm-conductor-tests:
+ #  docker:
+ #   - image: holochain/holochain-rust:latest
+ #  steps:
+ #   - checkout
 
-   - run:
-       name: wasm conductor tests
-       command: nix-shell --run hc-conductor-wasm-test
+ #   - run:
+ #       name: wasm conductor tests
+ #       command: nix-shell --run hc-conductor-wasm-test
 
- cold.ubuntu.bionic.auto:
-  docker:
-   - image: ubuntu:bionic
-  resource_class: xlarge
-  steps:
-   - checkout
-   - run: ./scripts/install/auto.sh
-   - run: make test
+ # cold.ubuntu.bionic.auto:
+ #  docker:
+ #   - image: ubuntu:bionic
+ #  resource_class: xlarge
+ #  steps:
+ #   - checkout
+ #   - run: ./scripts/install/auto.sh
+ #   - run: make test
 
- cold.ubuntu.xenial.auto:
-  docker:
-   - image: ubuntu:xenial
-  resource_class: xlarge
-  steps:
-   - checkout
-   - run: ./scripts/install/auto.sh
-   - run: make test
+ # cold.ubuntu.xenial.auto:
+ #  docker:
+ #   - image: ubuntu:xenial
+ #  resource_class: xlarge
+ #  steps:
+ #   - checkout
+ #   - run: ./scripts/install/auto.sh
+ #   - run: make test
 
- cold.debian.stable.auto:
-  docker:
-   - image: debian:stable
-  resource_class: xlarge
-  steps:
-   - checkout
-   - run: ./scripts/install/auto.sh
-   - run: make test
+ # cold.debian.stable.auto:
+ #  docker:
+ #   - image: debian:stable
+ #  resource_class: xlarge
+ #  steps:
+ #   - checkout
+ #   - run: ./scripts/install/auto.sh
+ #   - run: make test
 
- cold.mac.10.auto:
-  macos:
-   xcode: "10.2.0"
-  steps:
-   - checkout
-   - run: ./scripts/install/auto.sh
-   - run: make test
+ # cold.mac.10.auto:
+ #  macos:
+ #   xcode: "10.2.0"
+ #  steps:
+ #   - checkout
+ #   - run: ./scripts/install/auto.sh
+ #   - run: make test
 
- cold.mac.10.nix:
-  macos:
-   xcode: "10.2.0"
-  steps:
-   - checkout
-   - run:
-      name: Install and run all tests via nix
-      command: |
-       curl https://nixos.org/nix/install | sh
-       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
-       nix-shell --run hc-test
+ # cold.mac.10.nix:
+ #  macos:
+ #   xcode: "10.2.0"
+ #  steps:
+ #   - checkout
+ #   - run:
+ #      name: Install and run all tests via nix
+ #      command: |
+ #       curl https://nixos.org/nix/install | sh
+ #       . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
+ #       nix-shell --run hc-test
 
 workflows:
  version: 2
  tests:
   jobs:
-   - build
-   - fmt
+#   - build
+#   - fmt
    - app-spec-tests
-   - app-spec-proc-tests
-   - cluster-tests
-   - cli-tests
-   - wasm-conductor-tests
+#   - app-spec-proc-tests
+#   - cluster-tests
+#   - cli-tests
+#   - wasm-conductor-tests
 
  cold.ubuntu:
   jobs:
