fail builds with bad nightlies in readmes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -46,6 +46,22 @@ jobs:
           exit 1
         fi
 
+    # flag any references to a nightly version in a readme other than the
+    # ${date} in nix-shell
+    - run:
+       name: no readmes with bad rust nightly versions
+       command: |
+         # temporary avoid build fails due to greps
+         set +eo pipefail
+         export BAD_NIGHTLY=`nix-shell --run hc-readme-grep-nightly`
+         set -eo pipefail
+         if [[ $BAD_NIGHTLY ]]
+         then
+           echo "there is an incorrect nightly version in a readme file:"
+           echo $BAD_NIGHTLY
+           exit 1
+         fi
+
  app-spec-tests:
   docker:
    - image: holochain/holochain-rust:latest
